In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
df = pd.read_excel("Q_Commerce_Data_rating_Count.xlsx")

In [3]:
df

,Brand,Quantity,MRP,Price,Price_100_g,Discount,Rating,Rating_Count
0,Happilo,150,649,549,366.00,15,4.5,846
1,Happilo,200,465,249,124.50,46,4.4,1300
2,Happilo,400,825,665,166.25,31,4.4,4000
3,Happilo,250,125,59,23.60,52,4.2,1900
4,Happilo,500,450,315,63.00,30,4.5,1300
...,...,...,...,...,...,...,...,...
70,Healthy Master,250,394,301,120.40,24,4.4,121
71,Healthy Master,100,141,109,109.00,23,4.2,192
72,Healthy Master,100,141,109,109.00,23,4.6,242
73,Healthy Master,30,33,30,100.00,9,4.5,202
74,Healthy Master,100,141,109,109.00,23,4.7,195

In [4]:
df.columns = df.columns.str.strip()

In [5]:
df.columns

Index(['Brand', 'Quantity', 'MRP', 'Price', 'Price_100_g', 'Discount',
       'Rating', 'Rating_Count'],
      dtype='object')

In [22]:
target_columns = 'Rating_Count'
feature_columns = ['Quantity', 'MRP', 'Discount',]

In [23]:
analysis_df = df[feature_columns+[target_columns]].dropna()

In [24]:
for col in analysis_df.columns:
    analysis_df[col] =  pd.to_numeric(analysis_df[col], errors='coerce')

In [14]:
analysis_df

    Quantity  MRP  Price  Price_100_g  Discount  Rating  Rating_Count
0        150  649    549       366.00        15     4.5           846
1        200  465    249       124.50        46     4.4          1300
2        400  825    665       166.25        31     4.4          4000
3        250  125     59        23.60        52     4.2          1900
4        500  450    315        63.00        30     4.5          1300
..       ...  ...    ...          ...       ...     ...           ...
70       250  394    301       120.40        24     4.4           121
71       100  141    109       109.00        23     4.2           192
72       100  141    109       109.00        23     4.6           242
73        30   33     30       100.00         9     4.5           202
74       100  141    109       109.00        23     4.7           195

[75 rows x 7 columns]

In [25]:
analysis_df  = analysis_df.dropna()
analysis_df

    Quantity  MRP  Discount  Rating_Count
0        150  649        15           846
1        200  465        46          1300
2        400  825        31          4000
3        250  125        52          1900
4        500  450        30          1300
..       ...  ...       ...           ...
70       250  394        24           121
71       100  141        23           192
72       100  141        23           242
73        30   33         9           202
74       100  141        23           195

[75 rows x 4 columns]

In [26]:
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Quantity      75 non-null     int64
 1   MRP           75 non-null     int64
 2   Discount      75 non-null     int64
 3   Rating_Count  75 non-null     int64
dtypes: int64(4)
memory usage: 2.5 KB

In [27]:
x = analysis_df[feature_columns]
y = analysis_df[target_columns]
intercept = sm.add_constant(x)

In [28]:
intercept

    const  Quantity  MRP  Discount
0     1.0       150  649        15
1     1.0       200  465        46
2     1.0       400  825        31
3     1.0       250  125        52
4     1.0       500  450        30
..    ...       ...  ...       ...
70    1.0       250  394        24
71    1.0       100  141        23
72    1.0       100  141        23
73    1.0        30   33         9
74    1.0       100  141        23

[75 rows x 4 columns]

In [29]:
model = sm.OLS(y,intercept).fit()

In [33]:
model_summary = model.summary()

In [35]:
print(model_summary)

                            OLS Regression Results
==============================================================================
Dep. Variable:           Rating_Count   R-squared:                       0.134
Model:                            OLS   Adj. R-squared:                  0.097
Method:                 Least Squares   F-statistic:                     3.647
Date:                Tue, 05 May 2026   Prob (F-statistic):             0.0166
Time:                        12:15:34   Log-Likelihood:                -756.41
No. Observations:                  75   AIC:                             1521.
Df Residuals:                      71   BIC:                             1530.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2106.6621   1566.299      1.345      0.183   -1016.450    5229.774
Quantity      -8.6208      4.555     -1.893      0.062     -17.702       0.461
MRP            0.0743      1.454      0.051      0.959      -2.824       2.973
Discount     141.8666     53.414      2.656      0.010      35.361     248.372
==============================================================================
Omnibus:                       75.157   Durbin-Watson:                   1.556
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              646.765
Skew:                           2.996   Prob(JB):                    3.60e-141
Kurtosis:                      16.079   Cond. No.                     1.77e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.77e+03. This might indicate that there are
strong multicollinearity or other numerical problems.